apiVersion: v1
kind: Service
metadata:
  name: erikwutest-headless
  labels:
    app: erikwutest
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/scheme: "http"
spec:
  clusterIP: None  # This makes it a headless service
  selector:
    app: erikwutest
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
# Keep the original ClusterIP service for regular traffic if needed
apiVersion: v1
kind: Service
metadata:
  name: erikwutest-service
  labels:
    app: erikwutest
spec:
  selector:
    app: erikwutest
  type: ClusterIP
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP